Feature: add Obsidian folder option
saberzero1/quartz-syncer pull request #14
Opened 2024-05-21 01:46 UTC by mbbroberg

Closes #13

2024-05-21 10:21 UTC, saberzero1 requested changes
Thanks for the pr, I'll test it later today.

2024-05-21 10:21 UTC, saberzero1 commented on src/repositoryConnection/RepositoryConnection.ts
> -				"GET /repos/{owner}/{repo}/contents/{path}",
This is not a redundant path. `contents` is part of the GitHub REST api path to the root of a git project. Removing `contents` from the path breaks the ability to publish multiple files at once.

2024-05-21 10:21 UTC, saberzero1 commented on src/repositoryConnection/RepositoryConnection.ts
> -				"DELETE /repos/{owner}/{repo}/contents/{path}",
Ditto

2024-05-21 10:21 UTC, saberzero1 commented on src/repositoryConnection/RepositoryConnection.ts
> -				"PUT /repos/{owner}/{repo}/contents/{path}",
Ditto

2024-05-23 12:02 UTC, mbbroberg commented
@saberzero1 I'm working to remove that commit, but so you understand why: I removed that path because I correlated it to the additional `content` at the beginning of [commits like this one](https://github.com/mbbroberg/mossy-mental-models/commit/3fc2bc0366affc5abb9fb93f04dc0fc1e78a48b3). Once removed, I was able to map successfully to my file structure. Is there anything you noticed about what you see in [my commit history](https://github.com/mbbroberg/mossy-mental-models/commits/v4/) to help resolve this issue as well?

2024-05-23 12:14 UTC, saberzero1 commented
I think the problem is the method of link resolution.

I use absolute path and it seems to work fine. You seem to use shortest path, which apparently doesn't work.

I'll test your code to confirm if it works for both shortest path and absolute path.

Ultimately I should probably let users configure their preferred option. Or perhaps get their preferred option from their `quartz.config.ts` file.

2024-05-23 12:23 UTC, mbbroberg commented
@saberzero1 that's definitely it -- I do use shortest path. I backed out of the change but there's a bug in that behavior as noted. I'll consider that out of scope for this feature. Thanks!

2024-05-23 12:24 UTC, mbbroberg commented on main.ts
> +	obsidianRootFolder: "",
```suggestion
	obsidianRootFolder: "",
```

2025-05-21 20:22 UTC, closed without merging